-- Esquema do Voz Discente para Postgres (Supabase).
-- Cole no SQL Editor do Supabase e rode uma vez.
--
-- Atenção: "user" é palavra reservada no Postgres, por isso aparece sempre entre aspas.

CREATE TABLE "user" (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             varchar(80)  NOT NULL UNIQUE,
    password             varchar(200) NOT NULL,
    role                 varchar(50)  NOT NULL DEFAULT 'aluno',
    first_name           varchar(80),
    last_name            varchar(80),
    must_change_password boolean      NOT NULL DEFAULT false
);

CREATE TABLE subject (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

-- Quais disciplinas cada professor leciona.
CREATE TABLE user_subjects (
    user_id    integer NOT NULL REFERENCES "user"(id),
    subject_id integer NOT NULL REFERENCES subject(id),
    PRIMARY KEY (user_id, subject_id)
);

CREATE TABLE tema (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id integer      NOT NULL REFERENCES subject(id),
    nome       varchar(120) NOT NULL
);

CREATE TABLE feedback (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id              integer      NOT NULL REFERENCES "user"(id),
    subject_id              integer      NOT NULL REFERENCES subject(id),
    tema_id                 integer      REFERENCES tema(id),

    active_participation    integer      NOT NULL,
    task_completion         integer      NOT NULL,
    motivation_interest     integer      NOT NULL,
    welcoming_environment   integer      NOT NULL,
    comprehension_effort    integer      NOT NULL,
    content_connection      integer      NOT NULL,
    additional_comment      varchar(500) NOT NULL,

    compound                double precision,
    neg                     double precision,
    neu                     double precision,
    pos                     double precision,
    token_attributions_json text,
    shap_attributions_json  text,

    overall_score           double precision NOT NULL,
    created_at              timestamp DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE student_risk_analysis (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        integer     NOT NULL REFERENCES "user"(id),
    subject_id        integer     NOT NULL REFERENCES subject(id),
    average_score     double precision NOT NULL,
    average_sentiment double precision,
    feedback_count    integer     NOT NULL,
    risk_score        double precision NOT NULL,
    risk_level        varchar(20) NOT NULL,
    last_updated      timestamp DEFAULT (now() AT TIME ZONE 'utc')
);

-- Índices para as consultas que o dashboard e o histórico realmente fazem.
CREATE INDEX idx_feedback_student  ON feedback (student_id);
CREATE INDEX idx_feedback_subject  ON feedback (subject_id);
CREATE INDEX idx_feedback_criado   ON feedback (created_at DESC);
CREATE INDEX idx_tema_subject      ON tema (subject_id);
CREATE INDEX idx_risco_subject     ON student_risk_analysis (subject_id);
CREATE UNIQUE INDEX idx_risco_aluno_disciplina
    ON student_risk_analysis (student_id, subject_id);
